name: Build and Release .NET Application
permissions:
  contents: write
  actions: write
on:
  push:
    branches:
      - main  # Or your default branch

jobs:
  build-and-release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore solution/mcronberg/cs/VideoPoker.sln

      - name: Build and publish
        run: dotnet publish solution/mcronberg/cs/VideoPoker.ConsoleApp/VideoPoker.ConsoleApp.csproj -c Release -o ./publish --no-restore
        
      - name: List contents of publish directory
        run: |
          Get-ChildItem -Path ./publish -Recurse | ForEach-Object { Write-Host $_.FullName }
        shell: pwsh

      - name: Generate and set tag
        id: set_tag
        shell: pwsh
        run: |
          $NEW_TAG = Get-Date -Format "yyyy-MM-dd-HHmmss"
          echo "::set-output name=tag::$NEW_TAG"
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Zip Application Files
        run: Compress-Archive -Path ./publish/VideoPoker.ConsoleApp.exe, ./publish/VideoPoker.Core.dll -DestinationPath ./publish/VideoPokerRelease.zip
        shell: pwsh

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.set_tag.outputs.tag }}
          release_name: Release ${{ steps.set_tag.outputs.tag }}
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./publish/VideoPokerRelease.zip
          asset_name: VideoPokerRelease.zip
          asset_content_type: application/zip
